### ISSUE TITLE
Wrong file type in folders in file_organizer.py

### ISSUE THREAD

**Issue by dv1sual** [herokunt/python-scripts#1]
I think line 101 and 102 needs to be in "Videos_dir" and line 107 needs to be in Music_dir:

This is the code now:

`  MUSIC_DIR: set([
    '.mov',
    '.mkv',
    '.mp3',
  ]),
  VIDEOS_DIR: set([
    '.mp4',
    '.wav',
  ]),
}`

This is how is supposed to be:

`  MUSIC_DIR: set([
    '.wav',
    '.mp3',
  ]),
  VIDEOS_DIR: set([
    '.mp4',
    '.mov',
    '.mkv',
  ]),
}`

**Comment by D10f** [comment]
Thanks for the issue, I have just updated and added a bunch of new file formats including one for executables. I'm hesitant to add too many though since everyone is a different about how they organized their stuff, so I'll look into summarizing the most used extensions as defaults only.

Let me know if you find something else out of place, cheers!

**Comment by dv1sual** [comment]
Now it's just perfect, and almost all the file extensions are covered!
